"""Add missing columns

Revision ID: e542fddbff6f
Revises: 001
Create Date: 2025-11-29 10:47:50.215453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e542fddbff6f'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'starter'::character varying"))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('departments', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.alter_column('departments', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.create_foreign_key(op.f('fk_departments_manager_id_employees'), 'departments', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('departments', 'updated_at')
    op.drop_column('departments', 'is_active')
    op.add_column('employees', sa.Column('manager_id', sa.UUID(), nullable=True))
    op.add_column('employees', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('employees', sa.Column('job_title', sa.String(length=200), nullable=True))
    op.add_column('employees', sa.Column('vop_participation_rate', sa.Numeric(precision=3, scale=2), nullable=True))
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('employees', 'vop_opted_out',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_magic_link_token'), table_name='employees')
    op.create_unique_constraint(op.f('uq_employees_magic_link_token'), 'employees', ['magic_link_token'])
    op.create_foreign_key(op.f('fk_employees_manager_id_employees'), 'employees', 'employees', ['manager_id'], ['id'], ondelete='SET NULL')
    op.drop_column('employees', 'employee_id')
    op.add_column('users', sa.Column('department_id', sa.UUID(), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'manager'::character varying"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_users_company_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_foreign_key(op.f('fk_users_department_id_departments'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.add_column('vop_actions', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('vop_actions', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('vop_actions', sa.Column('visible_to_employees', sa.Boolean(), nullable=False))
    op.add_column('vop_actions', sa.Column('priority', sa.String(length=20), nullable=False))
    op.alter_column('vop_actions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'new'::character varying"))
    op.alter_column('vop_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_actions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vop_actions_company_id'), table_name='vop_actions')
    op.drop_index(op.f('ix_vop_actions_status'), table_name='vop_actions')
    op.drop_constraint(op.f('fk_vop_actions_department_id_departments'), 'vop_actions', type_='foreignkey')
    op.drop_column('vop_actions', 'internal_notes')
    op.drop_column('vop_actions', 'department_id')
    op.add_column('vop_alerts', sa.Column('is_resolved', sa.Boolean(), nullable=False))
    op.add_column('vop_alerts', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.alter_column('vop_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'medium'::character varying"))
    op.alter_column('vop_alerts', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('vop_alerts', 'trigger_keywords',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vop_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vop_alerts_company_id'), table_name='vop_alerts')
    op.drop_index(op.f('ix_vop_alerts_type'), table_name='vop_alerts')
    op.drop_constraint(op.f('fk_vop_alerts_conversation_id_vop_conversations'), 'vop_alerts', type_='foreignkey')
    op.drop_constraint(op.f('fk_vop_alerts_read_by_users'), 'vop_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vop_alerts_conversation_id_vop_conversations'), 'vop_alerts', 'vop_conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_column('vop_alerts', 'read_by')
    op.alter_column('vop_conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('vop_conversations', 'transcript_reviewed_by_employee',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_conversations', 'fallback_to_text',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vop_conversations_employee_id'), table_name='vop_conversations')
    op.drop_index(op.f('ix_vop_conversations_survey_id'), table_name='vop_conversations')
    op.add_column('vop_surveys', sa.Column('target_employee_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('vop_surveys', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('vop_surveys', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('vop_surveys', 'frequency',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.alter_column('vop_surveys', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('vop_surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_surveys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vop_surveys_company_id'), table_name='vop_surveys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vop_surveys_company_id'), 'vop_surveys', ['company_id'], unique=False)
    op.alter_column('vop_surveys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_surveys', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_surveys', 'questions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('vop_surveys', 'frequency',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'monthly'::character varying"))
    op.alter_column('vop_surveys', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('vop_surveys', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('vop_surveys', 'target_employee_ids')
    op.create_index(op.f('ix_vop_conversations_survey_id'), 'vop_conversations', ['survey_id'], unique=False)
    op.create_index(op.f('ix_vop_conversations_employee_id'), 'vop_conversations', ['employee_id'], unique=False)
    op.alter_column('vop_conversations', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_conversations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_conversations', 'fallback_to_text',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_conversations', 'transcript_reviewed_by_employee',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_conversations', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.add_column('vop_alerts', sa.Column('read_by', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_vop_alerts_conversation_id_vop_conversations'), 'vop_alerts', type_='foreignkey')
    op.create_foreign_key(op.f('fk_vop_alerts_read_by_users'), 'vop_alerts', 'users', ['read_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_vop_alerts_conversation_id_vop_conversations'), 'vop_alerts', 'vop_conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_vop_alerts_type'), 'vop_alerts', ['type'], unique=False)
    op.create_index(op.f('ix_vop_alerts_company_id'), 'vop_alerts', ['company_id'], unique=False)
    op.alter_column('vop_alerts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('vop_alerts', 'trigger_keywords',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('vop_alerts', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('vop_alerts', 'severity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'medium'::character varying"))
    op.drop_column('vop_alerts', 'resolved_at')
    op.drop_column('vop_alerts', 'is_resolved')
    op.add_column('vop_actions', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('vop_actions', sa.Column('internal_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_vop_actions_department_id_departments'), 'vop_actions', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_vop_actions_status'), 'vop_actions', ['status'], unique=False)
    op.create_index(op.f('ix_vop_actions_company_id'), 'vop_actions', ['company_id'], unique=False)
    op.alter_column('vop_actions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_actions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('vop_actions', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'new'::character varying"))
    op.drop_column('vop_actions', 'priority')
    op.drop_column('vop_actions', 'visible_to_employees')
    op.drop_column('vop_actions', 'notes')
    op.drop_column('vop_actions', 'description')
    op.drop_constraint(op.f('fk_users_department_id_departments'), 'users', type_='foreignkey')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_company_id'), 'users', ['company_id'], unique=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'manager'::character varying"))
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'department_id')
    op.add_column('employees', sa.Column('employee_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_employees_manager_id_employees'), 'employees', type_='foreignkey')
    op.drop_constraint(op.f('uq_employees_magic_link_token'), 'employees', type_='unique')
    op.create_index(op.f('ix_employees_magic_link_token'), 'employees', ['magic_link_token'], unique=False)
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.alter_column('employees', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('employees', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('employees', 'vop_opted_out',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('employees', 'last_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('employees', 'vop_participation_rate')
    op.drop_column('employees', 'job_title')
    op.drop_column('employees', 'phone')
    op.drop_column('employees', 'manager_id')
    op.add_column('departments', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('departments', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('fk_departments_manager_id_employees'), 'departments', type_='foreignkey')
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.alter_column('departments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('departments', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('departments', 'manager_id')
    op.alter_column('companies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('companies', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('companies', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'starter'::character varying"))
    # ### end Alembic commands ###
