"""add_item_type_description_and_isdefault_fields

Revision ID: c1310994d158
Revises: 1b7ebd476b75
Create Date: 2025-11-14 12:46:33.623768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1310994d158'
down_revision = '1b7ebd476b75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_type', sa.Column('description', sa.String(), nullable=True))
    op.add_column('item_type', sa.Column('isDefault', sa.Boolean(), nullable=False))
    op.alter_column('item_type', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('item_type', 'color',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('knowledge_item', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_knowledge_item_createdAt'), 'knowledge_item', ['createdAt'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_item_createdAt'), table_name='knowledge_item')
    op.alter_column('knowledge_item', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item_type', 'color',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('item_type', 'icon',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('item_type', 'isDefault')
    op.drop_column('item_type', 'description')
    # ### end Alembic commands ###
