#!/bin/bash
# Generate a safe .env with unique secrets for local/dev usage.

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="${ROOT_DIR}/.env"

POSTGRES_USER="${POSTGRES_USER:-speak_admin}"
POSTGRES_DB="${POSTGRES_DB:-vop}"

if [ -z "${POSTGRES_PASSWORD:-}" ]; then
    POSTGRES_PASSWORD="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(24))
PY
)"
fi

if [ -z "${JWT_SECRET_KEY:-}" ]; then
    JWT_SECRET_KEY="$(python3 - <<'PY'
import secrets
print(secrets.token_urlsafe(48))
PY
)"
fi

if [ -z "${DATABASE_URL:-}" ]; then
    DATABASE_URL="postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
fi

if [ -f "${ENV_FILE}" ] && [ "${OVERWRITE_ENV:-}" != "1" ]; then
    echo "Existing .env detected. Re-run with OVERWRITE_ENV=1 to regenerate."
    exit 1
fi

if [ -f "${ENV_FILE}" ] && [ "${BACKUP_ENV:-}" = "1" ]; then
    backup="${ENV_FILE}.bak.$(date +%Y%m%d%H%M%S)"
    cp "${ENV_FILE}" "${backup}"
    echo "Backed up existing .env to ${backup}"
fi

cat > "${ENV_FILE}" <<EOF
# Generated by scripts/generate_env.sh
# Add optional keys from .env.example if needed.

# Database
POSTGRES_USER=${POSTGRES_USER}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=${POSTGRES_DB}
DATABASE_URL=${DATABASE_URL}

# Authentication
JWT_SECRET_KEY=${JWT_SECRET_KEY}

# AI (optional)
GEMINI_API_KEY=
GEMINI_MODEL=models/gemini-2.5-flash-native-audio-preview-12-2025
EOF

echo "Wrote ${ENV_FILE}"
